# Generated by Django 5.2.1 on 2025-10-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Concepto')),
                ('type', models.CharField(choices=[('enrollment', 'Matrícula'), ('monthly', 'Pensión Mensual'), ('supplies', 'Útiles Escolares'), ('uniform', 'Uniforme'), ('transport', 'Transporte'), ('food', 'Alimentación'), ('extra', 'Actividad Extracurricular'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('report_type', models.CharField(choices=[('bulletin', 'Boletín Individual'), ('course_summary', 'Resumen de Curso'), ('attendance_report', 'Reporte de Asistencia'), ('grade_analysis', 'Análisis de Rendimiento'), ('student_certificate', 'Certificado de Estudiante'), ('course_list', 'Lista de Curso')], max_length=50, verbose_name='Tipo de Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('template_content', models.TextField(help_text='HTML template del reporte')),
                ('css_styles', models.TextField(blank=True, help_text='CSS personalizado para el reporte')),
                ('parameters', models.JSONField(default=dict, help_text='Parámetros configurables del reporte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('bulletin', 'Boletín Individual'), ('course_summary', 'Resumen de Curso'), ('attendance_report', 'Reporte de Asistencia'), ('grade_analysis', 'Análisis de Rendimiento'), ('enrollment_list', 'Lista de Matrícula'), ('payment_report', 'Reporte de Pagos'), ('behavioral_report', 'Reporte de Comportamiento')], max_length=30, verbose_name='Tipo de Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file_path', models.FileField(upload_to='reports/', verbose_name='Archivo')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros del Reporte')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Año Académico')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.course', verbose_name='Curso')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Reporte Académico',
                'verbose_name_plural': 'Reportes Académicos',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pagado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('partial', 'Pago Parcial'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia Bancaria'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.student', verbose_name='Estudiante')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.paymentconcept', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-due_date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Reporte')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('file_path', models.FileField(upload_to='reports/%Y/%m/', verbose_name='Archivo')),
                ('parameters_used', models.JSONField(default=dict, verbose_name='Parámetros Utilizados')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('holiday', 'Festivo'), ('vacation', 'Vacaciones'), ('exam_period', 'Período de Exámenes'), ('enrollment', 'Matrícula'), ('graduation', 'Graduación'), ('meeting', 'Reunión'), ('activity', 'Actividad Especial'), ('no_classes', 'Sin Clases')], max_length=20, verbose_name='Tipo de Evento')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('affects_all_grades', models.BooleanField(default=True, verbose_name='Afecta a Todos los Grados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('specific_grades', models.ManyToManyField(blank=True, to='academics.grade', verbose_name='Grados Específicos')),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Certificado de Nacimiento'), ('vaccination_card', 'Carnet de Vacunas'), ('medical_certificate', 'Certificado Médico'), ('academic_transcript', 'Certificado de Notas'), ('photo', 'Fotografía'), ('id_copy', 'Copia de Documento'), ('guardian_id', 'Documento del Acudiente'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to='student_documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('is_required', models.BooleanField(default=False, verbose_name='Documento Requerido')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.student', verbose_name='Estudiante')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento de Estudiante',
                'verbose_name_plural': 'Documentos de Estudiantes',
                'ordering': ['student__last_name', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Fecha de Matrícula')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('transferred', 'Trasladado'), ('graduated', 'Graduado'), ('suspended', 'Suspendido'), ('withdrawn', 'Retirado')], default='active', max_length=20, verbose_name='Estado')),
                ('enrollment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Matrícula')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pensión Mensual')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Año Académico')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course', verbose_name='Curso')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Matriculado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-academic_year__start_date', 'student__last_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
