# Generated by Django 5.2.1 on 2025-10-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_extended', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcriteria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='graderecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='graderecord',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='graderecord',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='GradingScale',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='studentgradesummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentgradesummary',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentgradesummary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentgradesummary',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['order', 'start_time'], 'verbose_name': 'Franja Horaria', 'verbose_name_plural': 'Franjas Horarias'},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_break',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='EvaluationCriteria',
        ),
        migrations.DeleteModel(
            name='GradeRecord',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='StudentGradeSummary',
        ),
    ]
