# Generated by Django 5.2.1 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_extended', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
