# Generated by Django 5.2.1 on 2025-10-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_extended', '0003_course_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveIntegerField(help_text='Horas semanales para esta materia en este grado', verbose_name='Horas por Semana')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Es Obligatoria')),
                ('semester', models.CharField(choices=[('anual', 'Anual'), ('primer_semestre', 'Primer Semestre'), ('segundo_semestre', 'Segundo Semestre')], default='anual', max_length=20, verbose_name='Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.grade', verbose_name='Grado')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Asignación de Materia a Grado',
                'verbose_name_plural': 'Asignaciones de Materias a Grados',
                'ordering': ['grade__order', 'subject__area', 'subject__name'],
                'unique_together': {('grade', 'subject', 'semester')},
            },
        ),
    ]
