# Generated by Django 5.2.1 on 2025-10-21 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_extended', '0004_gradesubjectassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')], verbose_name='Día de la Semana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.academicyear', verbose_name='Año Académico')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.classroom', verbose_name='Salón')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics_extended.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.subject', verbose_name='Materia')),
                ('teacher', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_extended.timeslot', verbose_name='Franja Horaria')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['weekday', 'time_slot__order'],
                'unique_together': {('classroom', 'time_slot', 'weekday', 'academic_year'), ('course', 'time_slot', 'weekday', 'academic_year'), ('teacher', 'time_slot', 'weekday', 'academic_year')},
            },
        ),
    ]
