# Generated by Django 5.2.1 on 2025-10-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('profesional', 'Profesional'), ('especialista', 'Especialista'), ('magister', 'Magíster'), ('doctorado', 'Doctorado')], max_length=20, verbose_name='Nivel Educativo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Graduación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Institución de Estudios'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Perfil Completo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(default='es', max_length=10, verbose_name='Idioma Preferido'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Notificaciones Activadas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Padre/Tutor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Padre/Tutor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_guardian_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del Padre/Tutor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Profesional'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialización'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario de Trabajo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de Experiencia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
