# Generated by Django 5.2.1 on 2025-10-19 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_extend_userprofile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('group_type', models.CharField(choices=[('academic', 'Académico'), ('departmental', 'Departamental'), ('functional', 'Funcional'), ('distribution', 'Lista de Distribución')], default='functional', max_length=20, verbose_name='Tipo de Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('allow_self_join', models.BooleanField(default=False, verbose_name='Permitir Auto-unirse')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible Públicamente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Grupo de Usuarios',
                'verbose_name_plural': 'Grupos de Usuarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('leader', 'Líder'), ('moderator', 'Moderador'), ('observer', 'Observador')], default='member', max_length=20, verbose_name='Rol en el Grupo')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Membresía Activa')),
                ('can_invite_others', models.BooleanField(default=False, verbose_name='Puede Invitar Otros')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones Habilitadas')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.usergroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Membresía de Grupo',
                'verbose_name_plural': 'Membresías de Grupo',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
