# Generated by Django 5.2.1 on 2025-10-19 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usergroup_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025', max_length=4, verbose_name='Año Académico')),
                ('grade', models.CharField(choices=[('preescolar', 'Preescolar'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Séptimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Décimo'), ('once', 'Once')], max_length=20, verbose_name='Grado')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Sección')),
                ('status', models.CharField(choices=[('enrolled', 'Matriculado'), ('active', 'Activo'), ('inactive', 'Inactivo'), ('withdrawn', 'Retirado'), ('graduated', 'Graduado'), ('transferred', 'Trasladado')], default='enrolled', max_length=20, verbose_name='Estado')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Colegio Anterior')),
                ('has_special_needs', models.BooleanField(default=False, verbose_name='Necesidades Especiales')),
                ('special_needs_description', models.TextField(blank=True, verbose_name='Descripción Necesidades Especiales')),
                ('parent_guardian_name', models.CharField(max_length=100, verbose_name='Nombre del Padre/Acudiente')),
                ('parent_guardian_phone', models.CharField(max_length=15, verbose_name='Teléfono del Acudiente')),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Acudiente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_students', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Director de Grupo')),
                ('student', models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula de Estudiante',
                'verbose_name_plural': 'Matrículas de Estudiantes',
                'ordering': ['-academic_year', 'grade', 'section', 'student__last_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
