# Generated by Django 5.2.1 on 2025-10-19 18:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Año Académico')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Año Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del Grado')),
                ('level', models.CharField(choices=[('primaria', 'Primaria'), ('bachillerato', 'Bachillerato')], max_length=20, verbose_name='Nivel')),
                ('numeric_grade', models.PositiveIntegerField(verbose_name='Grado Numérico')),
                ('order', models.PositiveIntegerField(help_text='Para ordenar en listas', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Materia')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('area', models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales'), ('ingles', 'Inglés'), ('educacion_fisica', 'Educación Física'), ('educacion_artistica', 'Educación Artística'), ('etica', 'Ética y Valores'), ('religion', 'Religión'), ('tecnologia', 'Tecnología e Informática'), ('filosofia', 'Filosofía'), ('quimica', 'Química'), ('fisica', 'Física'), ('biologia', 'Biología')], max_length=30, verbose_name='Área')),
                ('hours_per_week', models.PositiveIntegerField(verbose_name='Horas por Semana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('1', 'Primer Período'), ('2', 'Segundo Período'), ('3', 'Tercer Período'), ('4', 'Cuarto Período')], max_length=1, verbose_name='Período')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Período Actual')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['academic_year', 'number'],
                'unique_together': {('academic_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'Sección A'), ('B', 'Sección B'), ('C', 'Sección C'), ('D', 'Sección D')], max_length=1, verbose_name='Sección')),
                ('max_students', models.PositiveIntegerField(default=20, verbose_name='Máximo de Estudiantes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Año Académico')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_courses', to=settings.AUTH_USER_MODEL, verbose_name='Director de Curso')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['grade__order', 'section'],
                'unique_together': {('grade', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Código Estudiantil')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('graduated', 'Graduado'), ('transferred', 'Trasladado')], default='active', max_length=20, verbose_name='Estado')),
                ('enrollment_date', models.DateField(verbose_name='Fecha de Matrícula')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('guardian_name', models.CharField(max_length=200, verbose_name='Nombre del Acudiente')),
                ('guardian_relationship', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='Teléfono del Acudiente')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Acudiente')),
                ('medical_info', models.TextField(blank=True, verbose_name='Información Médica')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course', verbose_name='Curso Actual')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['course__grade__level', 'course__section', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('type', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo'), ('neutral', 'Neutral')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('discipline', 'Disciplina'), ('participation', 'Participación'), ('collaboration', 'Colaboración'), ('respect', 'Respeto'), ('responsibility', 'Responsabilidad'), ('academic', 'Académico'), ('social', 'Social')], max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('action_taken', models.TextField(blank=True, verbose_name='Acción Tomada')),
                ('requires_followup', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('parent_notified', models.BooleanField(default=False, verbose_name='Padre Notificado')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='academics.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro de Comportamiento',
                'verbose_name_plural': 'Registros de Comportamiento',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='Nombre de la Actividad')),
                ('activity_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Examen'), ('homework', 'Tarea'), ('project', 'Proyecto'), ('participation', 'Participación'), ('workshop', 'Taller'), ('lab', 'Laboratorio'), ('oral_exam', 'Examen Oral'), ('written_exam', 'Examen Escrito'), ('group_work', 'Trabajo en Grupo')], max_length=20, verbose_name='Tipo de Actividad')),
                ('grade_value', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Calificación')),
                ('date_recorded', models.DateField(verbose_name='Fecha de Registro')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicperiod', verbose_name='Período')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Registro de Calificación',
                'verbose_name_plural': 'Registros de Calificaciones',
                'ordering': ['-date_recorded', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardanza'), ('justified', 'Falta Justificada'), ('early_departure', 'Salida Temprana')], max_length=20, verbose_name='Estado')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Llegada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('justification', models.TextField(blank=True, verbose_name='Justificación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Año Académico')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course', verbose_name='Curso')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Materia')),
                ('teacher', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignación de Materia',
                'verbose_name_plural': 'Asignaciones de Materias',
                'unique_together': {('teacher', 'subject', 'course', 'academic_year')},
            },
        ),
    ]
